// Pragmatics4 stimuli: likelihood scale ("Absolutely Impossible" → "Absolutely Certain")
// Items with alternatives show both utterances before revealing which was said.
// Observed utterance is the stronger form for with-alternatives items, weaker for without.

var main_stimuli_gradable_meanings = [[{
  'scenario_id': 'pvt21_revised37',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Maria and Patrick are walking out of a movie theatre and discussing a documentary they just watched about a family that lost their home in a fire. Maria lets out a sigh and turns to Patrick.',
  'question': 'How likely is it that Maria teared up during the documentary?',
  'observed_utterance': 'What a tragic story.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Maria',
  'secondName': 'Patrick'
},
{
  'scenario_id': 'pvt21_revised2',
  'scenario_type': 'strong_no_alts',
  'scenario': 'William and Katherine are walking through an affluent neighbourhood with many mansions. As they stop to admire one mansion in particular, William turns to Katherine.',
  'question': 'How likely is it that this mansion has more than 20 rooms?',
  'observed_utterance': 'Damn, this thing is huge.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'William',
  'secondName': 'Katherine'
},
{
  'scenario_id': 'pvt21_revised5',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Amanda and Paul arrive at their restaurant for dinner. Amanda glances around the dining area and turns to Paul.',
  'question': 'How likely are they to get a table?',
  'observed_utterance': 'This place is full.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Amanda',
  'secondName': 'Paul'
},
{
  'scenario_id': 'pvt21_revised25',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Sharon is preparing dinner in the kitchen where her son Jason is trying to help. When Jason walks closer to the stove, Sharon turns to Jason.',
  'question': 'How likely is Jason to burn himself if he touches the pot?',
  'observed_utterance': 'Careful, the pot is hot.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Sharon',
  'secondName': 'Jason'
},
{
  'scenario_id': 'pvt21_revised23',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Jose and Jasmine have just attended a charity concert that raised significant funds for a local shelter. As they leave, Jose turns to Jasmine.',
  'question': "How likely is it for Jose's ears to still be ringing from the concert?",
  'observed_utterance': 'The crowd was deafening.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jose',
  'secondName': 'Jasmine'
},
{
  'scenario_id': 'pvt21_revised33',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Catherine and Charles are visiting a small village during a roadtrip. After walking up a hill, they arrive at a viewpoint overlooking the entire village. Catherine turns to Charles.',
  'question': 'How likely are Catherine and Charles to take a photo of the view?',
  'observed_utterance': 'What a pretty view.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Catherine',
  'secondName': 'Charles',
  'alternatives': ['What a pretty view.', 'What a beautiful view.']
},
{
  'scenario_id': 'pvt21_revised40',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Albert and Jessica are exploring a historic castle. They come across a wall that impresses them both with its size. Albert puts his hand against the wall and turns to Jessica.',
  'question': 'How likely is it that a cannonball could not pierce through the wall?',
  'observed_utterance': 'This thing feels thick.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Albert',
  'secondName': 'Jessica'
},
{
  'scenario_id': 'pvt21_revised28',
  'scenario_type': 'strong_with_alts',
  'scenario': "Ronald and Jess are sitting in a conference room brainstorming ideas for a new promotional campaign. After listening to Ronald's latest proposal, Jess turns to Ronald.",
  'question': 'How likely is it that this idea is novel?',
  'observed_utterance': "That's a bizarre idea.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jess',
  'secondName': 'Ronald',
  'alternatives': ["That's an unusual idea.", "That's a bizarre idea."]
},
{
  'scenario_id': 'pvt21_revised1',
  'scenario_type': 'strong_with_alts',
  'scenario': "Joshua and Beverly, who are walking over to a friend's house downtown, come across a group of protesters. Beverly turns to Joshua.",
  'question': 'How likely is Beverly to suggest they find a different way?',
  'observed_utterance': 'They look furious.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Beverly',
  'secondName': 'Joshua',
  'alternatives': ['They look angry.', 'They look furious.']
},
{
  'scenario_id': 'pvt21_revised29',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Gerald and Margaret are attending a live musical concert. As the last song finishes, Gerald turns to Margaret.',
  'question': 'How likely are Gerald and Margaret to give the performance a five-star rating?',
  'observed_utterance': 'That was a good show.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Gerald',
  'secondName': 'Margaret'
},
{
  'scenario_id': 'pvt21_revised42',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Jacqueline and Christian are observing a caterpillar which is resting on a leaf. They are interested in finding out how caterpillars move. Jacqueline turns to Christian.',
  'question': "How likely is it for someone to not notice the caterpillar's movement?",
  'observed_utterance': 'Its movements are imperceptible.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jacqueline',
  'secondName': 'Christian'
},
{
  'scenario_id': 'pvt21_revised39',
  'scenario_type': 'weak_no_alts',
  'scenario': 'James and Lauren are preparing a healthy snack in the kitchen. James picks up a banana, notices its texture, and turns to Lauren.',
  'question': 'How likely is the banana to have gone bad?',
  'observed_utterance': 'This banana feels kind of soft.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'James',
  'secondName': 'Lauren'
},
{
  'scenario_id': 'pvt21_revised10',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Linda and Kenneth are sitting around a campfire after a long day of hiking. As the stars begin to twinkle above them, Linda looks to Kenneth.',
  'question': 'How likely do you think it is for Linda to put on an extra layer?',
  'observed_utterance': "It's starting to get a bit cold.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Linda',
  'secondName': 'Kenneth'
},
{
  'scenario_id': 'pvt21_revised15',
  'scenario_type': 'strong_with_alts',
  'scenario': "Larry and Tina are driving through their state's farmland. As they pass the farmlands, Larry glances at the ground and turns to Tina.",
  'question': 'How likely is it that it has not rained in the last month?',
  'observed_utterance': 'This grass looks arid.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Larry',
  'secondName': 'Tina',
  'alternatives': ['This grass looks dry.', 'This grass looks arid.']
},
{
  'scenario_id': 'pvt21_revised30',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Timothy and Julia are hiking in a forest when Timothy brushes against a thorny bush. He grimaces as he turns to Julia.',
  'question': 'How likely is Timothy to require first aid?',
  'observed_utterance': 'Ouch! That hurts.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Timothy',
  'secondName': 'Julia',
  'alternatives': ['Ouch! That hurts.', "Ouch! That's painful."]
},
{
  'scenario_id': 'pvt21_revised45',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Harold and Harper, two mechanics, are working on a car that just came in. After a long afternoon of tuning up the engine, Harold turns to Harper.',
  'question': 'How likely is it for Harold to have to wait before touching the engine?',
  'observed_utterance': "That's quite hot.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Harold',
  'secondName': 'Harper',
  'alternatives': ["That's quite warm.", "That's quite hot."]
},
{
  'scenario_id': 'pvt21_revised34',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Max and Judy are sitting in a library, studying for their final exams. Max turns to Judy.',
  'question': 'How likely is it that people are whispering around Max and Judy?',
  'observed_utterance': 'I like how silent it is here.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Max',
  'secondName': 'Judy',
  'alternatives': ['I like how quiet it is here.',
    'I like how silent it is here.']
},
{
  'scenario_id': 'pvt21_revised36',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Megan has just run into her new colleague Caleb. After chatting briefly, Megan returns to her desk where her colleague Jerome is sitting. She sits down and turns to him.',
  'question': 'How likely is Megan to report Caleb to human resources?',
  'observed_utterance': 'I just talked to Caleb for the first time. He was so mean.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Megan',
  'secondName': 'Jerome',
  'alternatives': ['I just talked to Caleb for the first time. He was so unfriendly.',
    'I just talked to Caleb for the first time. He was so mean.']
},
{
  'scenario_id': 'pvt21_revised43',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Pamela and Bruce are exiting their classroom after having taken an exam. As they walk to their next class, Pamela turns to Bruce.',
  'question': 'How likely is it that Pamela failed the exam?',
  'observed_utterance': 'That exam was tough.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Pamela',
  'secondName': 'Bruce',
  'alternatives': ['That exam was tough.', 'That exam was impossible.']
},
{
  'scenario_id': 'pvt21_revised27',
  'scenario_type': 'strong_with_alts',
  'scenario': "Jeremy and Marcus are attending a gaming convention. They're discussing a new game that was showcased during the event, particularly the visuals it offered. Jeremy turns to Marcus.",
  'question': 'How likely is the game to win an award for its graphics?',
  'observed_utterance': 'The graphics were great.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jeremy',
  'secondName': 'Marcus',
  'alternatives': ['The graphics were nice.', 'The graphics were great.']
}],
[{
  'scenario_id': 'pvt21_revised37',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Maria and Patrick are walking out of a movie theatre and discussing a documentary they just watched about a family that lost their home in a fire. Maria lets out a sigh and turns to Patrick.',
  'question': 'How likely is it that Maria teared up during the documentary?',
  'observed_utterance': 'What a sad story.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Maria',
  'secondName': 'Patrick'
},
{
  'scenario_id': 'pvt21_revised2',
  'scenario_type': 'weak_no_alts',
  'scenario': 'William and Katherine are walking through an affluent neighbourhood with many mansions. As they stop to admire one mansion in particular, William turns to Katherine.',
  'question': 'How likely is it that this mansion has more than 20 rooms?',
  'observed_utterance': 'Damn, this thing is big!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'William',
  'secondName': 'Katherine'
},
{
  'scenario_id': 'pvt21_revised5',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Amanda and Paul arrive at their restaurant for dinner. Amanda glances around the dining area and turns to Paul.',
  'question': 'How likely are they to get a table?',
  'observed_utterance': 'This place is busy!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Amanda',
  'secondName': 'Paul',
  'alternatives': ['This place is busy!', 'This place is full.']
},
{
  'scenario_id': 'pvt21_revised25',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Sharon is preparing dinner in the kitchen where her son Jason is trying to help. When Jason walks closer to the stove, Sharon turns to Jason.',
  'question': 'How likely is Jason to burn himself if he touches the pot?',
  'observed_utterance': 'Careful, the pot is boiling.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Sharon',
  'secondName': 'Jason'
},
{
  'scenario_id': 'pvt21_revised23',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Jose and Jasmine have just attended a charity concert that raised significant funds for a local shelter. As they leave, Jose turns to Jasmine.',
  'question': "How likely is it for Jose's ears to still be ringing from the concert?",
  'observed_utterance': 'The crowd was loud.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jose',
  'secondName': 'Jasmine'
},
{
  'scenario_id': 'pvt21_revised33',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Catherine and Charles are visiting a small village during a roadtrip. After walking up a hill, they arrive at a viewpoint overlooking the entire village. Catherine turns to Charles.',
  'question': 'How likely are Catherine and Charles to take a photo of the view?',
  'observed_utterance': 'What a pretty view.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Catherine',
  'secondName': 'Charles'
},
{
  'scenario_id': 'pvt21_revised40',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Albert and Jessica are exploring a historic castle. They come across a wall that impresses them both with its size. Albert puts his hand against the wall and turns to Jessica.',
  'question': 'How likely is it that a cannonball could not pierce through the wall?',
  'observed_utterance': 'This thing feels impenetrable.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Albert',
  'secondName': 'Jessica'
},
{
  'scenario_id': 'pvt21_revised28',
  'scenario_type': 'weak_no_alts',
  'scenario': "Ronald and Jess are sitting in a conference room brainstorming ideas for a new promotional campaign. After listening to Ronald's latest proposal, Jess turns to Ronald.",
  'question': 'How likely is it that this idea is novel?',
  'observed_utterance': "That's an unusual idea.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jess',
  'secondName': 'Ronald'
},
{
  'scenario_id': 'pvt21_revised1',
  'scenario_type': 'strong_no_alts',
  'scenario': "Joshua and Beverly, who are walking over to a friend's house downtown, come across a group of protesters. Beverly turns to Joshua.",
  'question': 'How likely is Beverly to suggest they find a different way?',
  'observed_utterance': 'They look furious.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Beverly',
  'secondName': 'Joshua'
},
{
  'scenario_id': 'pvt21_revised29',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Gerald and Margaret are attending a live musical concert. As the last song finishes, Gerald turns to Margaret.',
  'question': 'How likely are Gerald and Margaret to give the performance a five-star rating?',
  'observed_utterance': 'That was a good show.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Gerald',
  'secondName': 'Margaret',
  'alternatives': ['That was a good show.', 'That was a great show.']
},
{
  'scenario_id': 'pvt21_revised42',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Jacqueline and Christian are observing a caterpillar which is resting on a leaf. They are interested in finding out how caterpillars move. Jacqueline turns to Christian.',
  'question': "How likely is it for someone to not notice the caterpillar's movement?",
  'observed_utterance': 'Its movements are tiny.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jacqueline',
  'secondName': 'Christian',
  'alternatives': ['Its movements are tiny.',
    'Its movements are imperceptible.']
},
{
  'scenario_id': 'pvt21_revised39',
  'scenario_type': 'strong_no_alts',
  'scenario': 'James and Lauren are preparing a healthy snack in the kitchen. James picks up a banana, notices its texture, and turns to Lauren.',
  'question': 'How likely is the banana to have gone bad?',
  'observed_utterance': 'This banana feels kind of mushy.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'James',
  'secondName': 'Lauren'
},
{
  'scenario_id': 'pvt21_revised10',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Linda and Kenneth are sitting around a campfire after a long day of hiking. As the stars begin to twinkle above them, Linda looks to Kenneth.',
  'question': 'How likely do you think it is for Linda to put on an extra layer?',
  'observed_utterance': "It's starting to get a bit cool.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Linda',
  'secondName': 'Kenneth'
},
{
  'scenario_id': 'pvt21_revised15',
  'scenario_type': 'weak_with_alts',
  'scenario': "Larry and Tina are driving through their state's farmland. As they pass the farmlands, Larry glances at the ground and turns to Tina.",
  'question': 'How likely is it that it has not rained in the last month?',
  'observed_utterance': 'This grass looks dry.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Larry',
  'secondName': 'Tina',
  'alternatives': ['This grass looks dry.', 'This grass looks arid.']
},
{
  'scenario_id': 'pvt21_revised30',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Timothy and Julia are hiking in a forest when Timothy brushes against a thorny bush. He grimaces as he turns to Julia.',
  'question': 'How likely is Timothy to require first aid?',
  'observed_utterance': "Ouch! That's painful.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Timothy',
  'secondName': 'Julia'
},
{
  'scenario_id': 'pvt21_revised45',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Harold and Harper, two mechanics, are working on a car that just came in. After a long afternoon of tuning up the engine, Harold turns to Harper.',
  'question': 'How likely is it for Harold to have to wait before touching the engine?',
  'observed_utterance': "That's quite warm.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Harold',
  'secondName': 'Harper',
  'alternatives': ["That's quite warm.", "That's quite hot."]
},
{
  'scenario_id': 'pvt21_revised34',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Max and Judy are sitting in a library, studying for their final exams. Max turns to Judy.',
  'question': 'How likely is it that people are whispering around Max and Judy?',
  'observed_utterance': 'I like how quiet it is here.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Max',
  'secondName': 'Judy'
},
{
  'scenario_id': 'pvt21_revised36',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Megan has just run into her new colleague Caleb. After chatting briefly, Megan returns to her desk where her colleague Jerome is sitting. She sits down and turns to him.',
  'question': 'How likely is Megan to report Caleb to human resources?',
  'observed_utterance': 'I just talked to Caleb for the first time. He was so unfriendly.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Megan',
  'secondName': 'Jerome'
},
{
  'scenario_id': 'pvt21_revised43',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Pamela and Bruce are exiting their classroom after having taken an exam. As they walk to their next class, Pamela turns to Bruce.',
  'question': 'How likely is it that Pamela failed the exam?',
  'observed_utterance': 'That exam was tough.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Pamela',
  'secondName': 'Bruce'
},
{
  'scenario_id': 'pvt21_revised27',
  'scenario_type': 'weak_no_alts',
  'scenario': "Jeremy and Marcus are attending a gaming convention. They're discussing a new game that was showcased during the event, particularly the visuals it offered. Jeremy turns to Marcus.",
  'question': 'How likely is the game to win an award for its graphics?',
  'observed_utterance': 'The graphics were nice.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jeremy',
  'secondName': 'Marcus'
}],
[{
  'scenario_id': 'pvt21_revised37',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Maria and Patrick are walking out of a movie theatre and discussing a documentary they just watched about a family that lost their home in a fire. Maria lets out a sigh and turns to Patrick.',
  'question': 'How likely is it that Maria teared up during the documentary?',
  'observed_utterance': 'What a sad story.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Maria',
  'secondName': 'Patrick',
  'alternatives': ['What a sad story.', 'What a tragic story.']
},
{
  'scenario_id': 'pvt21_revised24',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Marie and Jordan, two colleagues, are discussing the performance of a woman who interviewed for a position at their office.',
  'question': 'How likely is the candidate to get rejected?',
  'observed_utterance': 'I found her responses to be quite blunt.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Marie',
  'secondName': 'Jordan',
  'alternatives': ['I found her responses to be quite blunt.',
    'I found her answers to be quite rude.']
},
{
  'scenario_id': 'pvt21_revised5',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Amanda and Paul arrive at their restaurant for dinner. Amanda glances around the dining area and turns to Paul.',
  'question': 'How likely are they to get a table?',
  'observed_utterance': 'This place is full.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Amanda',
  'secondName': 'Paul',
  'alternatives': ['This place is busy!', 'This place is full.']
},
{
  'scenario_id': 'pvt21_revised44',
  'scenario_type': 'weak_no_alts',
  'scenario': "Ashley and Richard are hanging out at Richard's apartment. After Richard brings up a difficult topic, Ashley turns to Richard.",
  'question': 'How likely is it that Ashley and Richard talk about something else?',
  'observed_utterance': "I'm finding this conversation uncomfortable.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Ashley',
  'secondName': 'Richard'
},
{
  'scenario_id': 'pvt21_revised23',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Jose and Jasmine have just attended a charity concert that raised significant funds for a local shelter. As they leave, Jose turns to Jasmine.',
  'question': "How likely is it for Jose's ears to still be ringing from the concert?",
  'observed_utterance': 'The crowd was deafening.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jose',
  'secondName': 'Jasmine',
  'alternatives': ['The crowd was loud.', 'The crowd was deafening.']
},
{
  'scenario_id': 'pvt21_revised14',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Bobby is meeting up his friend Logan to catch up. When Bobby sees Logan, he notices that Logan has gotten a new haircut. When they meet, he notices that Logan has gotten a new haircut.',
  'question': "How likely is Bobby to ask Logan for his barber's name?",
  'observed_utterance': 'Logan, your hair looks great!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Bobby',
  'secondName': 'Logan'
},
{
  'scenario_id': 'pvt21_revised40',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Albert and Jessica are exploring a historic castle. They come across a wall that impresses them both with its size. Albert puts his hand against the wall and turns to Jessica.',
  'question': 'How likely is it that a cannonball could not pierce through the wall?',
  'observed_utterance': 'This thing feels thick.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Albert',
  'secondName': 'Jessica',
  'alternatives': ['This thing feels thick.',
    'This thing feels impenetrable.']
},
{
  'scenario_id': 'pvt21_revised11',
  'scenario_type': 'strong_no_alts',
  'scenario': "Daniel and Brenda are having coffee at a trendy café. Brenda just met Daniel's girlfriend for the first time, and she looks pleasantly surprised as she turns to Daniel.",
  'question': "How likely is it that Daniel's girlfriend is a model?",
  'observed_utterance': "You didn't tell me she was that beautiful.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Brenda',
  'secondName': 'Daniel'
},
{
  'scenario_id': 'pvt21_revised1',
  'scenario_type': 'weak_with_alts',
  'scenario': "Joshua and Beverly, who are walking over to a friend's house downtown, come across a group of protesters. Beverly turns to Joshua.",
  'question': 'How likely is Beverly to suggest they find a different way?',
  'observed_utterance': 'They look angry.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Beverly',
  'secondName': 'Joshua',
  'alternatives': ['They look angry.', 'They look furious.']
},
{
  'scenario_id': 'pvt21_revised38',
  'scenario_type': 'strong_no_alts',
  'scenario': "Tiffany and Matthew are academics at a university. Tiffany is expressing her opinion of Matthew's new research idea and turns to Matthew.",
  'question': 'How likely is it that Matthew receives a prize for his idea?',
  'observed_utterance': 'That was a brilliant idea.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Tiffany',
  'secondName': 'Matthew'
},
{
  'scenario_id': 'pvt21_revised42',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Jacqueline and Christian are observing a caterpillar which is resting on a leaf. They are interested in finding out how caterpillars move. Jacqueline turns to Christian.',
  'question': "How likely is it for someone to not notice the caterpillar's movement?",
  'observed_utterance': 'Its movements are tiny.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jacqueline',
  'secondName': 'Christian'
},
{
  'scenario_id': 'pvt21_revised32',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Hannah and Jacob just finished a meal at a new restaurant in town. As they are getting ready to pay the bill, Hannah turns to Jacob.',
  'question': 'How likely is Hannah to leave a larger-than-usual tip?',
  'observed_utterance': 'I like how friendly the staff was.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Hannah',
  'secondName': 'Jacob',
  'alternatives': ['I like how polite the staff was.',
    'I like how friendly the staff was.']
},
{
  'scenario_id': 'pvt21_revised10',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Linda and Kenneth are sitting around a campfire after a long day of hiking. As the stars begin to twinkle above them, Linda looks to Kenneth.',
  'question': 'How likely do you think it is for Linda to put on an extra layer?',
  'observed_utterance': "It's starting to get a bit cool.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Linda',
  'secondName': 'Kenneth',
  'alternatives': ["It's starting to get a bit cool.",
    "It's starting to get a bit cold."]
},
{
  'scenario_id': 'pvt21_revised47',
  'scenario_type': 'weak_no_alts',
  'scenario': "Jack has just gone out to buy some milk during which it rained unexpectedly. When Jack returns home, Judith, Jack's partner, turns to him.",
  'question': 'How likely is Jack to need to change into dry clothes?',
  'observed_utterance': 'You look a bit wet.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Judith',
  'secondName': 'Jack'
},
{
  'scenario_id': 'pvt21_revised30',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Timothy and Julia are hiking in a forest when Timothy brushes against a thorny bush. He grimaces as he turns to Julia.',
  'question': 'How likely is Timothy to require first aid?',
  'observed_utterance': "Ouch! That's painful.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Timothy',
  'secondName': 'Julia',
  'alternatives': ['Ouch! That hurts.', "Ouch! That's painful."]
},
{
  'scenario_id': 'pvt21_revised21',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Carl and Laura are at a comedy club, enjoying a night of stand-up performances. At the end of the night, Carl thinks back, chuckles and turns to Laura.',
  'question': 'How likely is Carl to recommend the comedian to his friends?',
  'observed_utterance': 'That guy was hilarious.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Carl',
  'secondName': 'Laura',
  'alternatives': ['That guy was funny.', 'That guy was hilarious.']
},
{
  'scenario_id': 'pvt21_revised34',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Max and Judy are sitting in a library, studying for their final exams. Max turns to Judy.',
  'question': 'How likely is it that people are whispering around Max and Judy?',
  'observed_utterance': 'I like how quiet it is here.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Max',
  'secondName': 'Judy',
  'alternatives': ['I like how quiet it is here.',
    'I like how silent it is here.']
},
{
  'scenario_id': 'pvt21_revised41',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Terry and Jenna are studying an old map. Terry points to a line on the map and turns to Jenna.',
  'question': 'How likely is it for someone to not notice the line Terry pointed to?',
  'observed_utterance': 'This line is invisible.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Terry',
  'secondName': 'Jenna',
  'alternatives': ['This line is thin.', 'This line is invisible.']
},
{
  'scenario_id': 'pvt21_revised43',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Pamela and Bruce are exiting their classroom after having taken an exam. As they walk to their next class, Pamela turns to Bruce.',
  'question': 'How likely is it that Pamela failed the exam?',
  'observed_utterance': 'That exam was impossible.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Pamela',
  'secondName': 'Bruce'
}],
[{
  'scenario_id': 'pvt21_revised37',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Maria and Patrick are walking out of a movie theatre and discussing a documentary they just watched about a family that lost their home in a fire. Maria lets out a sigh and turns to Patrick.',
  'question': 'How likely is it that Maria teared up during the documentary?',
  'observed_utterance': 'What a tragic story.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Maria',
  'secondName': 'Patrick',
  'alternatives': ['What a sad story.', 'What a tragic story.']
},
{
  'scenario_id': 'pvt21_revised24',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Marie and Jordan, two colleagues, are discussing the performance of a woman who interviewed for a position at their office.',
  'question': 'How likely is the candidate to get rejected?',
  'observed_utterance': 'I found her answers to be quite rude.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Marie',
  'secondName': 'Jordan',
  'alternatives': ['I found her responses to be quite blunt.',
    'I found her answers to be quite rude.']
},
{
  'scenario_id': 'pvt21_revised5',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Amanda and Paul arrive at their restaurant for dinner. Amanda glances around the dining area and turns to Paul.',
  'question': 'How likely are they to get a table?',
  'observed_utterance': 'This place is busy!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Amanda',
  'secondName': 'Paul'
},
{
  'scenario_id': 'pvt21_revised44',
  'scenario_type': 'strong_no_alts',
  'scenario': "Ashley and Richard are hanging out at Richard's apartment. After Richard brings up a difficult topic, Ashley turns to Richard.",
  'question': 'How likely is it that Ashley and Richard talk about something else?',
  'observed_utterance': "I'm finding this conversation painful.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Ashley',
  'secondName': 'Richard'
},
{
  'scenario_id': 'pvt21_revised23',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Jose and Jasmine have just attended a charity concert that raised significant funds for a local shelter. As they leave, Jose turns to Jasmine.',
  'question': "How likely is it for Jose's ears to still be ringing from the concert?",
  'observed_utterance': 'The crowd was loud.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jose',
  'secondName': 'Jasmine',
  'alternatives': ['The crowd was loud.', 'The crowd was deafening.']
},
{
  'scenario_id': 'pvt21_revised14',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Bobby is meeting up his friend Logan to catch up. When Bobby sees Logan, he notices that Logan has gotten a new haircut. When they meet, he notices that Logan has gotten a new haircut.',
  'question': "How likely is Bobby to ask Logan for his barber's name?",
  'observed_utterance': 'Logan, your hair looks nice!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Bobby',
  'secondName': 'Logan'
},
{
  'scenario_id': 'pvt21_revised40',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Albert and Jessica are exploring a historic castle. They come across a wall that impresses them both with its size. Albert puts his hand against the wall and turns to Jessica.',
  'question': 'How likely is it that a cannonball could not pierce through the wall?',
  'observed_utterance': 'This thing feels impenetrable.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Albert',
  'secondName': 'Jessica',
  'alternatives': ['This thing feels thick.',
    'This thing feels impenetrable.']
},
{
  'scenario_id': 'pvt21_revised11',
  'scenario_type': 'strong_with_alts',
  'scenario': "Daniel and Brenda are having coffee at a trendy café. Brenda just met Daniel's girlfriend for the first time, and she looks pleasantly surprised as she turns to Daniel.",
  'question': "How likely is it that Daniel's girlfriend is a model?",
  'observed_utterance': "You didn't tell me she was that beautiful.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Brenda',
  'secondName': 'Daniel',
  'alternatives': ["You didn't tell me she was that cute.",
    "You didn't tell me she was that beautiful."]
},
{
  'scenario_id': 'pvt21_revised1',
  'scenario_type': 'weak_no_alts',
  'scenario': "Joshua and Beverly, who are walking over to a friend's house downtown, come across a group of protesters. Beverly turns to Joshua.",
  'question': 'How likely is Beverly to suggest they find a different way?',
  'observed_utterance': 'They look angry.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Beverly',
  'secondName': 'Joshua'
},
{
  'scenario_id': 'pvt21_revised38',
  'scenario_type': 'weak_with_alts',
  'scenario': "Tiffany and Matthew are academics at a university. Tiffany is expressing her opinion of Matthew's new research idea and turns to Matthew.",
  'question': 'How likely is it that Matthew receives a prize for his idea?',
  'observed_utterance': 'That was a smart idea.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Tiffany',
  'secondName': 'Matthew',
  'alternatives': ['That was a smart idea.', 'That was a brilliant idea.']
},
{
  'scenario_id': 'pvt21_revised42',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Jacqueline and Christian are observing a caterpillar which is resting on a leaf. They are interested in finding out how caterpillars move. Jacqueline turns to Christian.',
  'question': "How likely is it for someone to not notice the caterpillar's movement?",
  'observed_utterance': 'Its movements are imperceptible.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jacqueline',
  'secondName': 'Christian',
  'alternatives': ['Its movements are tiny.',
    'Its movements are imperceptible.']
},
{
  'scenario_id': 'pvt21_revised32',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Hannah and Jacob just finished a meal at a new restaurant in town. As they are getting ready to pay the bill, Hannah turns to Jacob.',
  'question': 'How likely is Hannah to leave a larger-than-usual tip?',
  'observed_utterance': 'I like how polite the staff was.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Hannah',
  'secondName': 'Jacob'
},
{
  'scenario_id': 'pvt21_revised10',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Linda and Kenneth are sitting around a campfire after a long day of hiking. As the stars begin to twinkle above them, Linda looks to Kenneth.',
  'question': 'How likely do you think it is for Linda to put on an extra layer?',
  'observed_utterance': "It's starting to get a bit cold.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Linda',
  'secondName': 'Kenneth',
  'alternatives': ["It's starting to get a bit cool.",
    "It's starting to get a bit cold."]
},
{
  'scenario_id': 'pvt21_revised47',
  'scenario_type': 'weak_with_alts',
  'scenario': "Jack has just gone out to buy some milk during which it rained unexpectedly. When Jack returns home, Judith, Jack's partner, turns to him.",
  'question': 'How likely is Jack to need to change into dry clothes?',
  'observed_utterance': 'You look a bit wet.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Judith',
  'secondName': 'Jack',
  'alternatives': ['You look a bit wet.', 'You look soaked.']
},
{
  'scenario_id': 'pvt21_revised30',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Timothy and Julia are hiking in a forest when Timothy brushes against a thorny bush. He grimaces as he turns to Julia.',
  'question': 'How likely is Timothy to require first aid?',
  'observed_utterance': 'Ouch! That hurts.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Timothy',
  'secondName': 'Julia'
},
{
  'scenario_id': 'pvt21_revised21',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Carl and Laura are at a comedy club, enjoying a night of stand-up performances. At the end of the night, Carl thinks back, chuckles and turns to Laura.',
  'question': 'How likely is Carl to recommend the comedian to his friends?',
  'observed_utterance': 'That guy was funny.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Carl',
  'secondName': 'Laura'
},
{
  'scenario_id': 'pvt21_revised34',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Max and Judy are sitting in a library, studying for their final exams. Max turns to Judy.',
  'question': 'How likely is it that people are whispering around Max and Judy?',
  'observed_utterance': 'I like how silent it is here.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Max',
  'secondName': 'Judy'
},
{
  'scenario_id': 'pvt21_revised41',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Terry and Jenna are studying an old map. Terry points to a line on the map and turns to Jenna.',
  'question': 'How likely is it for someone to not notice the line Terry pointed to?',
  'observed_utterance': 'This line is thin.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Terry',
  'secondName': 'Jenna'
},
{
  'scenario_id': 'pvt21_revised43',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Pamela and Bruce are exiting their classroom after having taken an exam. As they walk to their next class, Pamela turns to Bruce.',
  'question': 'How likely is it that Pamela failed the exam?',
  'observed_utterance': 'That exam was impossible.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Pamela',
  'secondName': 'Bruce',
  'alternatives': ['That exam was tough.', 'That exam was impossible.']
}],
[{
  'scenario_id': 'pvt21_revised2',
  'scenario_type': 'strong_with_alts',
  'scenario': 'William and Katherine are walking through an affluent neighbourhood with many mansions. As they stop to admire one mansion in particular, William turns to Katherine.',
  'question': 'How likely is it that this mansion has more than 20 rooms?',
  'observed_utterance': 'Damn, this thing is huge.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'William',
  'secondName': 'Katherine',
  'alternatives': ['Damn, this thing is big!', 'Damn, this thing is huge.']
},
{
  'scenario_id': 'pvt21_revised24',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Marie and Jordan, two colleagues, are discussing the performance of a woman who interviewed for a position at their office.',
  'question': 'How likely is the candidate to get rejected?',
  'observed_utterance': 'I found her responses to be quite blunt.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Marie',
  'secondName': 'Jordan'
},
{
  'scenario_id': 'pvt21_revised25',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Sharon is preparing dinner in the kitchen where her son Jason is trying to help. When Jason walks closer to the stove, Sharon turns to Jason.',
  'question': 'How likely is Jason to burn himself if he touches the pot?',
  'observed_utterance': 'Careful, the pot is hot.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Sharon',
  'secondName': 'Jason',
  'alternatives': ['Careful, the pot is hot.',
    'Careful, the pot is boiling.']
},
{
  'scenario_id': 'pvt21_revised44',
  'scenario_type': 'weak_with_alts',
  'scenario': "Ashley and Richard are hanging out at Richard's apartment. After Richard brings up a difficult topic, Ashley turns to Richard.",
  'question': 'How likely is it that Ashley and Richard talk about something else?',
  'observed_utterance': "I'm finding this conversation uncomfortable.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Ashley',
  'secondName': 'Richard',
  'alternatives': ["I'm finding this conversation uncomfortable.",
    "I'm finding this conversation painful."]
},
{
  'scenario_id': 'pvt21_revised33',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Catherine and Charles are visiting a small village during a roadtrip. After walking up a hill, they arrive at a viewpoint overlooking the entire village. Catherine turns to Charles.',
  'question': 'How likely are Catherine and Charles to take a photo of the view?',
  'observed_utterance': 'What a beautiful view.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Catherine',
  'secondName': 'Charles',
  'alternatives': ['What a pretty view.', 'What a beautiful view.']
},
{
  'scenario_id': 'pvt21_revised14',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Bobby is meeting up his friend Logan to catch up. When Bobby sees Logan, he notices that Logan has gotten a new haircut. When they meet, he notices that Logan has gotten a new haircut.',
  'question': "How likely is Bobby to ask Logan for his barber's name?",
  'observed_utterance': 'Logan, your hair looks nice!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Bobby',
  'secondName': 'Logan',
  'alternatives': ['Logan, your hair looks nice!',
    'Logan, your hair looks great!']
},
{
  'scenario_id': 'pvt21_revised28',
  'scenario_type': 'strong_no_alts',
  'scenario': "Ronald and Jess are sitting in a conference room brainstorming ideas for a new promotional campaign. After listening to Ronald's latest proposal, Jess turns to Ronald.",
  'question': 'How likely is it that this idea is novel?',
  'observed_utterance': "That's a bizarre idea.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jess',
  'secondName': 'Ronald'
},
{
  'scenario_id': 'pvt21_revised11',
  'scenario_type': 'weak_no_alts',
  'scenario': "Daniel and Brenda are having coffee at a trendy café. Brenda just met Daniel's girlfriend for the first time, and she looks pleasantly surprised as she turns to Daniel.",
  'question': "How likely is it that Daniel's girlfriend is a model?",
  'observed_utterance': "You didn't tell me she was that cute.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Brenda',
  'secondName': 'Daniel'
},
{
  'scenario_id': 'pvt21_revised29',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Gerald and Margaret are attending a live musical concert. As the last song finishes, Gerald turns to Margaret.',
  'question': 'How likely are Gerald and Margaret to give the performance a five-star rating?',
  'observed_utterance': 'That was a great show.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Gerald',
  'secondName': 'Margaret'
},
{
  'scenario_id': 'pvt21_revised38',
  'scenario_type': 'weak_no_alts',
  'scenario': "Tiffany and Matthew are academics at a university. Tiffany is expressing her opinion of Matthew's new research idea and turns to Matthew.",
  'question': 'How likely is it that Matthew receives a prize for his idea?',
  'observed_utterance': 'That was a smart idea.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Tiffany',
  'secondName': 'Matthew'
},
{
  'scenario_id': 'pvt21_revised39',
  'scenario_type': 'weak_with_alts',
  'scenario': 'James and Lauren are preparing a healthy snack in the kitchen. James picks up a banana, notices its texture, and turns to Lauren.',
  'question': 'How likely is the banana to have gone bad?',
  'observed_utterance': 'This banana feels kind of soft.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'James',
  'secondName': 'Lauren',
  'alternatives': ['This banana feels kind of soft.',
    'This banana feels kind of mushy.']
},
{
  'scenario_id': 'pvt21_revised32',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Hannah and Jacob just finished a meal at a new restaurant in town. As they are getting ready to pay the bill, Hannah turns to Jacob.',
  'question': 'How likely is Hannah to leave a larger-than-usual tip?',
  'observed_utterance': 'I like how friendly the staff was.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Hannah',
  'secondName': 'Jacob'
},
{
  'scenario_id': 'pvt21_revised15',
  'scenario_type': 'weak_no_alts',
  'scenario': "Larry and Tina are driving through their state's farmland. As they pass the farmlands, Larry glances at the ground and turns to Tina.",
  'question': 'How likely is it that it has not rained in the last month?',
  'observed_utterance': 'This grass looks dry.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Larry',
  'secondName': 'Tina'
},
{
  'scenario_id': 'pvt21_revised47',
  'scenario_type': 'strong_with_alts',
  'scenario': "Jack has just gone out to buy some milk during which it rained unexpectedly. When Jack returns home, Judith, Jack's partner, turns to him.",
  'question': 'How likely is Jack to need to change into dry clothes?',
  'observed_utterance': 'You look soaked.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Judith',
  'secondName': 'Jack',
  'alternatives': ['You look a bit wet.', 'You look soaked.']
},
{
  'scenario_id': 'pvt21_revised45',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Harold and Harper, two mechanics, are working on a car that just came in. After a long afternoon of tuning up the engine, Harold turns to Harper.',
  'question': 'How likely is it for Harold to have to wait before touching the engine?',
  'observed_utterance': "That's quite hot.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Harold',
  'secondName': 'Harper'
},
{
  'scenario_id': 'pvt21_revised21',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Carl and Laura are at a comedy club, enjoying a night of stand-up performances. At the end of the night, Carl thinks back, chuckles and turns to Laura.',
  'question': 'How likely is Carl to recommend the comedian to his friends?',
  'observed_utterance': 'That guy was hilarious.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Carl',
  'secondName': 'Laura'
},
{
  'scenario_id': 'pvt21_revised36',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Megan has just run into her new colleague Caleb. After chatting briefly, Megan returns to her desk where her colleague Jerome is sitting. She sits down and turns to him.',
  'question': 'How likely is Megan to report Caleb to human resources?',
  'observed_utterance': 'I just talked to Caleb for the first time. He was so unfriendly.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Megan',
  'secondName': 'Jerome',
  'alternatives': ['I just talked to Caleb for the first time. He was so unfriendly.',
    'I just talked to Caleb for the first time. He was so mean.']
},
{
  'scenario_id': 'pvt21_revised41',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Terry and Jenna are studying an old map. Terry points to a line on the map and turns to Jenna.',
  'question': 'How likely is it for someone to not notice the line Terry pointed to?',
  'observed_utterance': 'This line is invisible.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Terry',
  'secondName': 'Jenna'
},
{
  'scenario_id': 'pvt21_revised27',
  'scenario_type': 'strong_no_alts',
  'scenario': "Jeremy and Marcus are attending a gaming convention. They're discussing a new game that was showcased during the event, particularly the visuals it offered. Jeremy turns to Marcus.",
  'question': 'How likely is the game to win an award for its graphics?',
  'observed_utterance': 'The graphics were great.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jeremy',
  'secondName': 'Marcus'
}],
[{
  'scenario_id': 'pvt21_revised2',
  'scenario_type': 'weak_with_alts',
  'scenario': 'William and Katherine are walking through an affluent neighbourhood with many mansions. As they stop to admire one mansion in particular, William turns to Katherine.',
  'question': 'How likely is it that this mansion has more than 20 rooms?',
  'observed_utterance': 'Damn, this thing is big!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'William',
  'secondName': 'Katherine',
  'alternatives': ['Damn, this thing is big!', 'Damn, this thing is huge.']
},
{
  'scenario_id': 'pvt21_revised24',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Marie and Jordan, two colleagues, are discussing the performance of a woman who interviewed for a position at their office.',
  'question': 'How likely is the candidate to get rejected?',
  'observed_utterance': 'I found her answers to be quite rude.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Marie',
  'secondName': 'Jordan'
},
{
  'scenario_id': 'pvt21_revised25',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Sharon is preparing dinner in the kitchen where her son Jason is trying to help. When Jason walks closer to the stove, Sharon turns to Jason.',
  'question': 'How likely is Jason to burn himself if he touches the pot?',
  'observed_utterance': 'Careful, the pot is boiling.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Sharon',
  'secondName': 'Jason',
  'alternatives': ['Careful, the pot is hot.',
    'Careful, the pot is boiling.']
},
{
  'scenario_id': 'pvt21_revised44',
  'scenario_type': 'strong_with_alts',
  'scenario': "Ashley and Richard are hanging out at Richard's apartment. After Richard brings up a difficult topic, Ashley turns to Richard.",
  'question': 'How likely is it that Ashley and Richard talk about something else?',
  'observed_utterance': "I'm finding this conversation painful.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Ashley',
  'secondName': 'Richard',
  'alternatives': ["I'm finding this conversation uncomfortable.",
    "I'm finding this conversation painful."]
},
{
  'scenario_id': 'pvt21_revised33',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Catherine and Charles are visiting a small village during a roadtrip. After walking up a hill, they arrive at a viewpoint overlooking the entire village. Catherine turns to Charles.',
  'question': 'How likely are Catherine and Charles to take a photo of the view?',
  'observed_utterance': 'What a beautiful view.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Catherine',
  'secondName': 'Charles'
},
{
  'scenario_id': 'pvt21_revised14',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Bobby is meeting up his friend Logan to catch up. When Bobby sees Logan, he notices that Logan has gotten a new haircut. When they meet, he notices that Logan has gotten a new haircut.',
  'question': "How likely is Bobby to ask Logan for his barber's name?",
  'observed_utterance': 'Logan, your hair looks great!',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Bobby',
  'secondName': 'Logan',
  'alternatives': ['Logan, your hair looks nice!',
    'Logan, your hair looks great!']
},
{
  'scenario_id': 'pvt21_revised28',
  'scenario_type': 'weak_with_alts',
  'scenario': "Ronald and Jess are sitting in a conference room brainstorming ideas for a new promotional campaign. After listening to Ronald's latest proposal, Jess turns to Ronald.",
  'question': 'How likely is it that this idea is novel?',
  'observed_utterance': "That's an unusual idea.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jess',
  'secondName': 'Ronald',
  'alternatives': ["That's an unusual idea.", "That's a bizarre idea."]
},
{
  'scenario_id': 'pvt21_revised11',
  'scenario_type': 'weak_with_alts',
  'scenario': "Daniel and Brenda are having coffee at a trendy café. Brenda just met Daniel's girlfriend for the first time, and she looks pleasantly surprised as she turns to Daniel.",
  'question': "How likely is it that Daniel's girlfriend is a model?",
  'observed_utterance': "You didn't tell me she was that cute.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Brenda',
  'secondName': 'Daniel',
  'alternatives': ["You didn't tell me she was that cute.",
    "You didn't tell me she was that beautiful."]
},
{
  'scenario_id': 'pvt21_revised29',
  'scenario_type': 'strong_with_alts',
  'scenario': 'Gerald and Margaret are attending a live musical concert. As the last song finishes, Gerald turns to Margaret.',
  'question': 'How likely are Gerald and Margaret to give the performance a five-star rating?',
  'observed_utterance': 'That was a great show.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Gerald',
  'secondName': 'Margaret',
  'alternatives': ['That was a good show.', 'That was a great show.']
},
{
  'scenario_id': 'pvt21_revised38',
  'scenario_type': 'strong_with_alts',
  'scenario': "Tiffany and Matthew are academics at a university. Tiffany is expressing her opinion of Matthew's new research idea and turns to Matthew.",
  'question': 'How likely is it that Matthew receives a prize for his idea?',
  'observed_utterance': 'That was a brilliant idea.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Tiffany',
  'secondName': 'Matthew',
  'alternatives': ['That was a smart idea.', 'That was a brilliant idea.']
},
{
  'scenario_id': 'pvt21_revised39',
  'scenario_type': 'strong_with_alts',
  'scenario': 'James and Lauren are preparing a healthy snack in the kitchen. James picks up a banana, notices its texture, and turns to Lauren.',
  'question': 'How likely is the banana to have gone bad?',
  'observed_utterance': 'This banana feels kind of mushy.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'James',
  'secondName': 'Lauren',
  'alternatives': ['This banana feels kind of soft.',
    'This banana feels kind of mushy.']
},
{
  'scenario_id': 'pvt21_revised32',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Hannah and Jacob just finished a meal at a new restaurant in town. As they are getting ready to pay the bill, Hannah turns to Jacob.',
  'question': 'How likely is Hannah to leave a larger-than-usual tip?',
  'observed_utterance': 'I like how polite the staff was.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Hannah',
  'secondName': 'Jacob',
  'alternatives': ['I like how polite the staff was.',
    'I like how friendly the staff was.']
},
{
  'scenario_id': 'pvt21_revised15',
  'scenario_type': 'strong_no_alts',
  'scenario': "Larry and Tina are driving through their state's farmland. As they pass the farmlands, Larry glances at the ground and turns to Tina.",
  'question': 'How likely is it that it has not rained in the last month?',
  'observed_utterance': 'This grass looks arid.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Larry',
  'secondName': 'Tina'
},
{
  'scenario_id': 'pvt21_revised47',
  'scenario_type': 'strong_no_alts',
  'scenario': "Jack has just gone out to buy some milk during which it rained unexpectedly. When Jack returns home, Judith, Jack's partner, turns to him.",
  'question': 'How likely is Jack to need to change into dry clothes?',
  'observed_utterance': 'You look soaked.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Judith',
  'secondName': 'Jack'
},
{
  'scenario_id': 'pvt21_revised45',
  'scenario_type': 'weak_no_alts',
  'scenario': 'Harold and Harper, two mechanics, are working on a car that just came in. After a long afternoon of tuning up the engine, Harold turns to Harper.',
  'question': 'How likely is it for Harold to have to wait before touching the engine?',
  'observed_utterance': "That's quite warm.",
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Harold',
  'secondName': 'Harper'
},
{
  'scenario_id': 'pvt21_revised21',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Carl and Laura are at a comedy club, enjoying a night of stand-up performances. At the end of the night, Carl thinks back, chuckles and turns to Laura.',
  'question': 'How likely is Carl to recommend the comedian to his friends?',
  'observed_utterance': 'That guy was funny.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Carl',
  'secondName': 'Laura',
  'alternatives': ['That guy was funny.', 'That guy was hilarious.']
},
{
  'scenario_id': 'pvt21_revised36',
  'scenario_type': 'strong_no_alts',
  'scenario': 'Megan has just run into her new colleague Caleb. After chatting briefly, Megan returns to her desk where her colleague Jerome is sitting. She sits down and turns to him.',
  'question': 'How likely is Megan to report Caleb to human resources?',
  'observed_utterance': 'I just talked to Caleb for the first time. He was so mean.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Megan',
  'secondName': 'Jerome'
},
{
  'scenario_id': 'pvt21_revised41',
  'scenario_type': 'weak_with_alts',
  'scenario': 'Terry and Jenna are studying an old map. Terry points to a line on the map and turns to Jenna.',
  'question': 'How likely is it for someone to not notice the line Terry pointed to?',
  'observed_utterance': 'This line is thin.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Terry',
  'secondName': 'Jenna',
  'alternatives': ['This line is thin.', 'This line is invisible.']
},
{
  'scenario_id': 'pvt21_revised27',
  'scenario_type': 'weak_with_alts',
  'scenario': "Jeremy and Marcus are attending a gaming convention. They're discussing a new game that was showcased during the event, particularly the visuals it offered. Jeremy turns to Marcus.",
  'question': 'How likely is the game to win an award for its graphics?',
  'observed_utterance': 'The graphics were nice.',
  'interpretations': ['Absolutely Impossible', 'Absolutely Certain'],
  'mainName': 'Jeremy',
  'secondName': 'Marcus',
  'alternatives': ['The graphics were nice.', 'The graphics were great.']
}]]